version: '2'
services:
    testy-app:
        image: testy
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://testy-mysql:3306/testy?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    testy-mysql:
        extends:
            file: mysql.yml
            service: testy-mysql
